add_newline = false
command_timeout = 2000

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '

[directory]
truncate_to_repo = false

[time]
disabled = false
# see https://docs.rs/chrono/latest/chrono/format/strftime/index.html
time_format = '%T, %F'

[gcloud]
disabled = true
